include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'
    
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

cache:
  paths:
    - frontend/.npm/

stages:
  - verify
  - test
  - build
  - deploy

spotbugs-sast:
  stage: verify
  rules:
    - changes:
        - frontend/*

sonarqube:
  stage: verify
  rules:
    - changes:
        - frontend/*
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner 
      -Dsonar.qualitygate.wait=false
      -Dsonar.sources=.
      -Dsonar.projectKey=${SONARQUBE_FRONTEND_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONARQUBE_LOGIN}

build-image:
  stage: build
  rules:
    - changes:
        - frontend/*
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - >
      docker build
      --tag $CI_REGISTRY_IMAGE/momo-store-frontend:$VERSION
      .
    - docker push $CI_REGISTRY_IMAGE/momo-store-frontend:$VERSION

deploy-k8s:
  stage: deploy
  rules:
    - changes:
        - frontend/*
  needs:
    - build-image
  environment:
    name: production-frontend
  image:
    name: alpine/k8s:1.24.13
  before_script:
    - mkdir ~/.kube
    - echo ${KUBECONFIG} > ~/.kube/config 
  script:
    - |
      kubectl config use-context yc-k8s-zonal-admin --namespace=default

      helm repo add nexus ${NEXUS_HELM_FRONTEND_REPO} --username ${NEXUS_USERNAME} --password ${NEXUS_PASSWORD}
      helm repo update
     
      helm upgrade --install momo-store-frontend \
      --kube-context yc-k8s-zonal-admin \
      --namespace default \
      --set image.tag="${VERSION}" \
      --set imagePullSecrets.value=${IMAGE_PULL_SECRET} \
      --atomic --timeout 15m nexus/momo-store-frontend
  after_script:
    - rm ~/.kube/config