include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'
    
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

cache:
  paths:
    - frontend/.npm/

stages:
  - verify
  - test
  - build
  - deploy

spotbugs-sast:
  stage: verify
  rules:
    - changes:
        - frontend/*

sonarqube:
  stage: verify
  rules:
    - changes:
        - frontend/*
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner 
      -Dsonar.qualitygate.wait=false
      -Dsonar.sources=.
      -Dsonar.projectKey=${SONARQUBE_FRONTEND_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONARQUBE_LOGIN}

build-image:
  stage: build
  rules:
    - changes:
        - frontend/*
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - >
      docker build
      --tag $CI_REGISTRY_IMAGE/momo-store-frontend:$VERSION
      .
    - docker push $CI_REGISTRY_IMAGE/momo-store-frontend:$VERSION
