include:
  - template: Security/SAST.gitlab-ci.yml
  - project: "templates/ci"
    file: "DockerInDockerTemplate.yml"

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - verify
  - test
  - build
  - deploy

spotbugs-sast:
  stage: verify
  rules:
    - changes:
        - backend/*

sonarqube:
  stage: verify
  rules:
    - changes:
        - backend/*
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd backend
    - >
      sonar-scanner 
      -Dsonar.qualitygate.wait=true
      -Dsonar.sources=.
      -Dsonar.projectKey=${SONARQUBE_BACKEND_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONARQUBE_LOGIN}

go-test:
  stage: test
  rules:
    - changes:
        - backend/*
  image: golang:1.17.13-bullseye
  script:
    - cd backend
    - go test -v ./...

build-image:
  stage: build
  rules:
    - changes:
        - backend/*
  needs:
    - go-test
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd backend
    - >
      docker build
      --build-arg VERSION=${VERSION}
      --tag $CI_REGISTRY_IMAGE/momo-store-backend:$VERSION
      .
    - docker push $CI_REGISTRY_IMAGE/momo-store-backend:$VERSION

deploy-k8s:
  stage: deploy
  rules:
    - changes:
        - backend/*
  needs:
    - build-image
  environment:
    name: production-backend 
  image:
    name: alpine/k8s:1.24.13
  before_script:
    - mkdir ~/.kube
    - echo ${KUBECONFIG} > ~/.kube/config 
  script:
    - |
      kubectl config use-context yc-k8s-zonal-admin --namespace=default

      helm repo add nexus ${NEXUS_HELM_BACKEND_REPO} --username ${NEXUS_USERNAME} --password ${NEXUS_PASSWORD}
      helm repo update
     
      helm upgrade --install momo-store-backend \
      --kube-context yc-k8s-zonal-admin \
      --namespace default \
      --set image.tag="${VERSION}" \
      --set imagePullSecrets.value="${IMAGE_PULL_SECRET}" \
      --atomic --timeout 15m nexus/momo-store-backend
  after_script:
    - rm ~/.kube/config