apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account }}
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer
  namespace: default
rules:         
  - apiGroups:  
      - ''      
    resources:
      - services
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.service_account }}-viewer"
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: viewer
subjects:
  - kind: ServiceAccount
    name: {{ .Values.service_account }}
    namespace: default