apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginxConfigMapName }}
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }

    http {
      server {

        listen {{ .Values.service.port }};

        location / {
          root   /usr/share/nginx/html;
          index  index.html;
          try_files $uri $uri/ /index.html;
        }

        location ~ ^/(?:products|categories|orders|metrics|auth/whoami) {
            proxy_pass http://{{ .Values.backendEndpoint }};
        }
      }
    }
