{
 "title": "Momo-store",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dumplings Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(dumplings_listing_count[5m])) by(id)"
    }
   ]
  },
  {
   "title": "Handler Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_timing_ms_bucket{handler=~\"/(products|categories|orders)/\"}[5m])) by (le, handler))"
    }
   ]
  },
  {
   "title": "Backend logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"momo-store-backend\"}"
    }
   ]
  },
  {
   "title": "Frontend logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"momo-store-frontend\"}"
    }
   ]
  }
 ]
}